const express = require('express');
const router = express.Router();
const {add_to_cart,view_my_cart,update_my_cart,delete_my_cart_item,delete_user_cart,view_one_cart,search_in_cart} = require('../../controller/cart');
const {ADD_TO_CART,VIEW_MY_CART,UPDATE_MY_CART,DELETE_MY_CART_ITEM,DELETE_USER_CART,VIEW_ONE_CART,SEARCH_IN_CART} = require('../../utils/config').ROUTES.CART;
router.post(ADD_TO_CART,add_to_cart);
router.get(VIEW_MY_CART,view_my_cart);
router.get(SEARCH_IN_CART,search_in_cart);
router.post(VIEW_ONE_CART,view_one_cart);
router.post(UPDATE_MY_CART,update_my_cart);
router.post(DELETE_MY_CART_ITEM,delete_my_cart_item);
router.post(DELETE_USER_CART,delete_user_cart);
module.exports = router;