const express = require('express');
const router = express.Router();
const {view_by_interest, rate_product,review_product, edit_rating, edit_review} = require('../../controller/product');
const {VIEW_BY_interest,RATE_PRODUCT,REVIEW_PRODUCT,EDIT_RATING,EDIT_REVIEW} = require('../../utils/config').ROUTES.PRODUCT;
router.get(VIEW_BY_interest,view_by_interest);
router.post(RATE_PRODUCT,rate_product);
router.post(REVIEW_PRODUCT,review_product);
router.post(EDIT_RATING,edit_rating);
router.post(EDIT_REVIEW,edit_review);
module.exports = router;