const express = require('express');
const router = express.Router();
const {login,forgot_pass,register,acc_recover, acc_recover_old_pass, check_email} = require('../../controller/user');
const {LOGIN,FORGOT_PASS,REGISTER,ACC_RECOVER,ACC_RECOVER_BY_OLD_PASS,CHECK_EMAIL} = require('../../utils/config').ROUTES.USER;
router.post(LOGIN,login);
router.post(FORGOT_PASS,forgot_pass);
router.post(REGISTER,register);
router.post(CHECK_EMAIL,check_email);
router.post(ACC_RECOVER,acc_recover);
router.post(ACC_RECOVER_BY_OLD_PASS,acc_recover_old_pass);
module.exports = router;