const express = require('express');
const router = express.Router();
const {view_all,delete_any_admin} = require('../../controller/deleted_admin');
const {VIEW_ALL,DELETE_ANY_ADMIN} = require('../../utils/config').ROUTES.DELETED_ADMINS;
const {DELETE_ANY_USER} = require('../../utils/config').ROUTES.DELETED_USERS;
const {delete_any_user} = require('../../controller/deleted_user');
router.get(VIEW_ALL,view_all);
router.post(DELETE_ANY_ADMIN,delete_any_admin);
router.post(DELETE_ANY_USER,delete_any_user);
module.exports = router;