const express = require('express');
const router = express.Router();
const {view_all,view_by_emailid,view_by_name,view_by_pincode,view_by_city,view_by_state ,view_by_user_id} = require('../../controller/deleted_user');
const {VIEW_ALL,VIEW_BY_EMAIL_ID,VIEW_BY_NAME,VIEW_BY_PINCODE,VIEW_BY_STATE,VIEW_BY_CITY,VIEW_BY_USER_ID} = require('../../utils/config').ROUTES.DELETED_USERS;
router.get(VIEW_ALL,view_all);
router.post(VIEW_BY_USER_ID,view_by_user_id);
router.post(VIEW_BY_EMAIL_ID,view_by_emailid);
router.post(VIEW_BY_NAME,view_by_name);
router.get(VIEW_BY_PINCODE,view_by_pincode);
router.get(VIEW_BY_CITY,view_by_city);
router.get(VIEW_BY_STATE,view_by_state);
module.exports = router;